http:
  routers:
    mailpit:
      rule: "Host(`mail.localhost`)"
      service: mailpit
      entryPoints:
        - web
    api-redirect:
      rule: "Host(`localhost`) && PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
    frontend:
      rule: "Host(`localhost`) && PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
    backend:
      rule: "Host(`api.localhost`)"
      service: backend
      entryPoints:
        - web

  services:
    mailpit:
      loadBalancer:
        servers:
          - url: "http://mailpit_dev:8025"
    frontend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4200"
    backend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5157"
