# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 0
    labels:
      - "github-actions dependencies"
      
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 0
    labels:
      - "docker image-version"
      
  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 0
    labels:
      - "npm dependencies"
    ignore:
      # ignore all patches
      - dependency-name: *
        update-types: ["version-update:semver-patch"]

      
  - package-ecosystem: "maven"
    directory: "/spring"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 0
    labels:
      - "maven dependencies"
    ignore:
      # ignore all patches
      - dependency-name: *
        update-types: ["version-update:semver-patch"]
