#
# Starts all services for e2e-Testing.
#
version: "3.9"
services:

  mail_hog:
    container_name: mailhog_e2e
    build:
      context: ../..
      dockerfile: docker/mailhog/Dockerfile
    restart: unless-stopped
    ports:
      - "31025:1025"
      - "38025:8025"

  db:
    container_name: database_e2e
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=anmelde_tool
      - POSTGRES_PASSWORD=anmelde_tool
      - POSTGRES_DB=anmelde_tool
    restart: unless-stopped
    ports:
      - "35432:5432"

  backend:
    container_name: backend_e2e
    build:
      context: ../..
      dockerfile: docker/spring/Dockerfile
    environment:
      - anmelde-tool.baseUrl=http://localhost
      - anmelde-tool.db.url=db
      - anmelde-tool.db.port=5432
    restart: unless-stopped
    ports:
      - "38080:38080"
    depends_on:
      - db

  frontend:
    container_name: frontend_e2e
    build:
      context: ../..
      dockerfile: docker/angular/Dockerfile
    environment:
      - CONFIG=e2e
    ports:
      - "4200:80"

  zitadel:
    container_name: zitadel_e2e
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:v2.31.3'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - ZITADEL_LOG_LEVEL=debug
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    container_name: cockroach_e2e
    restart: 'always'
    build:
      context: ../..
      dockerfile: docker/cockroach/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    volumes:
      - "../../docker/cockroach/data.tar.gz:/cockroach/data.tar.gz:rw"
      - "../../docker/cockroach/dump.sh:/cockroach/dump.sh:ro"
    ports:
      - '9090:8080'
      - '26257:26257'