#
# Starts shared infrastructure required for running certain services of the Movie-DB.
#
version: "3.9"
services:

  mail_hog:
    container_name: mailhog_dev
    build:
      context: ../..
      dockerfile: docker/mailhog/Dockerfile
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    container_name: database_dev
    image: postgres:latest
    environment:
      - POSTGRES_USER=anmelde_tool
      - POSTGRES_PASSWORD=anmelde_tool
      - POSTGRES_DB=anmelde_tool
    restart: unless-stopped
    ports:
      - "5432:5432"

  zitadel:
    container_name: zitadel_e2e
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:v2.27.0'
    # build:
    #   context: ../..
    #   dockerfile: docker/zitadel/Dockerfile
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - ZITADEL_LOG_LEVEL=debug
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=mail_hog:1025
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=noreply@localhost
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=ZITADEL
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    container_name: cockroach_e2e
    restart: 'always'
    image: 'cockroachdb/cockroach:v23.1.1'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'