#
# Starts shared infrastructure required for running certain services of the Movie-DB.
#
version: "3.9"
services:
  backend_db:
    container_name: database_dev
    image: postgres:15.10-alpine@sha256:93a6166360be8f1d116b7ea97ebb8dea9e2c9c746349e952738bbba72a961d7c
    environment:
      - POSTGRES_USER=scoutventure
      - POSTGRES_PASSWORD=scoutventure
      - POSTGRES_DB=scoutventure
    restart: unless-stopped
    ports:
      - "35432:5432"
  kc_database:
    container_name: kc_database
    image: postgres:16.6-alpine@sha256:aba1fab94626cf8b0f4549055214239a37e0a690f03f142b7bca05b9ed36c6db
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    restart: unless-stopped
    ports:
      - "5432:5432"
  kc_keycloak:
    container_name: kc_keycloak
    image: quay.io/keycloak/keycloak:25.0.6@sha256:82c5b7a110456dbd42b86ea572e728878549954cc8bd03cd65410d75328095d2
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-scoutventure.json
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kc_database:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    restart: unless-stopped
    volumes:
      - ../../docker/keycloak/realm-scoutventure.json:/opt/keycloak/data/import/realm-scoutventure.json
    command: start-dev --import-realm --verbose
    ports:
      - "8080:8080"
    depends_on:
      - kc_database
