#
# Starts shared infrastructure required for running certain services of the Movie-DB.
#
version: "3.9"
services:
  reverse-proxy:
    container_name: traefik_dev
    image: traefik:v3.3
    command:
      - "--api.insecure=true"  # Enable Traefik Dashboard
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../docker/traefik:/etc/traefik

  backend_db:
    container_name: database_dev
    image: postgres:17.2-alpine@sha256:0bcc5bbbb2aa9c9b4c6505845918c7eb55d783cf5c1f434fac33012579fb149d
    environment:
      - POSTGRES_USER=scoutventure
      - POSTGRES_PASSWORD=scoutventure
      - POSTGRES_DB=scoutventure
    restart: unless-stopped
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  mailpit:
    container_name: mailpit_dev
    image: axllent/mailpit:latest
    restart: unless-stopped
    volumes:
      - ../../docker/mailpit/data:/data
    ports:
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1