#
# Starts shared infrastructure required for running certain services of the Movie-DB.
#
version: "3.9"
services:
  backend_db:
    container_name: database_dev
    image: postgres:17.4-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    environment:
      - POSTGRES_USER=scoutventure
      - POSTGRES_PASSWORD=scoutventure
      - POSTGRES_DB=scoutventure
    restart: unless-stopped
    ports:
      - "35432:5432"
  kc_database:
    container_name: kc_database
    image: postgres:17.4-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    restart: unless-stopped
    ports:
      - "5432:5432"
  kc_keycloak:
    container_name: kc_keycloak
    image: quay.io/keycloak/keycloak:26.2.1@sha256:9869b88191392727f0be7301e53573cc39c13c9d9b9b08492c97d1ea40366eae
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-scoutventure.json
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kc_database:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    restart: unless-stopped
    volumes:
      - ../../docker/keycloak/realm-scoutventure.json:/opt/keycloak/data/import/realm-scoutventure.json
    command: start-dev --import-realm --verbose
    ports:
      - "8080:8080"
    depends_on:
      - kc_database
