#
# Starts shared infrastructure required for running certain services of the Movie-DB.
#
version: "3.9"
services:
  backend_db:
    container_name: database_dev
    image: postgres:17.3-alpine@sha256:80d3d7d6bb3ddb1e44b79612330f7bfc6c451f093f6dd14a1317e777a260b602
    environment:
      - POSTGRES_USER=scoutventure
      - POSTGRES_PASSWORD=scoutventure
      - POSTGRES_DB=scoutventure
    restart: unless-stopped
    ports:
      - "35432:5432"
  kc_database:
    container_name: kc_database
    image: postgres:17.3-alpine@sha256:80d3d7d6bb3ddb1e44b79612330f7bfc6c451f093f6dd14a1317e777a260b602
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    restart: unless-stopped
    ports:
      - "5432:5432"
  kc_keycloak:
    container_name: kc_keycloak
    image: quay.io/keycloak/keycloak:26.1.2@sha256:4704c51a25096e24379eafc81db5d7654a33b05e260a7eed2f4486b2daf00c45
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-scoutventure.json
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kc_database:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    restart: unless-stopped
    volumes:
      - ../../docker/keycloak/realm-scoutventure.json:/opt/keycloak/data/import/realm-scoutventure.json
    command: start-dev --import-realm --verbose
    ports:
      - "8080:8080"
    depends_on:
      - kc_database
