#
# Starts shared infrastructure required for running certain services of the Movie-DB.
#
version: "3.9"
services:
  backend_db:
    container_name: database_dev
    image: postgres:15.8-alpine@sha256:fa484d844b88ac34811daf3da66af1fd17e34b0e1ff5d1b6f904269c85890dc0
    environment:
      - POSTGRES_USER=scoutventure
      - POSTGRES_PASSWORD=scoutventure
      - POSTGRES_DB=scoutventure
    restart: unless-stopped
    ports:
      - "35432:5432"
  kc_database:
    container_name: kc_database
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    restart: unless-stopped
    ports:
      - "5432:5432"
  kc_keycloak:
    container_name: kc_keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-scoutventure.json
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kc_database:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    restart: unless-stopped
    volumes:
      - ../../docker/keycloak/realm-scoutventure.json:/opt/keycloak/data/import/realm-scoutventure.json
    command: start-dev --import-realm --verbose
    ports:
      - "8080:8080"
    depends_on:
      - kc_database
