server:
  port: 38080


spring:
  application:
    name: "ScoutVenture API and IAM"

  datasource:
    url: jdbc:postgresql://${scoutventure.db.url}:${scoutventure.db.port}/${scoutventure.db.db-name}?useSSL=${scoutventure.db.useSSL}&serverTimezone=Europe/Berlin
    username: ${scoutventure.db.username}
    password: ${scoutventure.db.password}

  liquibase:
    change-log: "classpath:/db/liquibase-changelog_testdata.xml"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${scoutventure.oauth2.issuer-uri}


scoutventure:
  baseUrl: "http://localhost:4200"
  oauth2:
    issuer-uri: "http://localhost:8080/realms/scoutventure"
    clientId: "d3b85e5bc91c40f2b8ea210b3f36f784@scoutventure-spa"
    secure-routes:
      - "/api"
  oidc:
    # The user with the superuser-sub will have full API access
    # The superuser-sub will be taken from the oauth2 jwt (subject) therefore it is none fungible
    superuser-sub: "44ceb6ed-8b4f-4ad4-b945-8fc7f7281599"
  db:
    url: localhost
    port: 35432
    useSSL: false
    username: "scoutventure"
    password: "scoutventure"
    db-name: "scoutventure"
  nami:
    uri: "https://nami.dpsg.de"
  logging:
    file:
      size-limit: 5MB
    directory: logs

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger/swagger.html
