server:
  port: 8443

spring:
  application:
    name: "ANMELDE_TOOL_BACKEND"

  datasource:
    url: jdbc:postgresql://${anmelde-tool.db.url}:${anmelde-tool.db.port}/${anmelde-tool.db.db-name}?useSSL=${anmelde-tool.db.useSSL}&serverTimezone=Europe/Berlin
    username: ${anmelde-tool.db.username}
    password: ${anmelde-tool.db.password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: "classpath:/db/liquibase-changelog_testdata.xml"
    drop-first: true

  mail:
    host: ${anmelde-tool.mail.host}
    port: ${anmelde-tool.mail.port}
    username: ${anmelde-tool.mail.username}
    password: ${anmelde-tool.mail.password}
    templates:
      path: "mail/templates"
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

anmelde-tool:
  baseUrl: "http://localhost:4200"
  db:
    url: localhost
    port: 5432
    useSSL: false
    username: "anmelde_tool"
    password: "anmelde_tool"
    db-name: "anmelde_tool"
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    noreply: noreply@localhost
  reset-password:
    cleanup:
      # Lifespan in minutes
      lifespan: 60
      cron: "0 0 * * * *"
    mail:
      pending-cron: "0 */10 * * * *"
  registration:
    cleanup:
      # Lifespan in minutes
      lifespan: 60
      cron: "0 0 * * * *"
    mail:
      pending-cron: "0 */10 * * * *"
  logging:
    file:
      size-limit: 5MB
    directory: logs

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
logging:
  level:
    org.springframework.security: DEBUG
