server:
  port: 38080


spring:
  application:
    name: "ScoutVenture API and IAM"
  jpa:
    defer-datasource-initialization: false
  datasource:
    scoutventure:
      url: jdbc:postgresql://${sv.db.url}:${sv.db.port}/${sv.db.db-name}?useSSL=${sv.db.useSSL}&serverTimezone=${sv.db.tz}
      username: ${sv.db.username}
      password: ${sv.db.password}
    keycloak:
      url: jdbc:postgresql://${sv.keycloak.db.url}:${sv.keycloak.db.port}/${sv.keycloak.db.db-name}?useSSL=${sv.keycloak.db.useSSL}&serverTimezone=${sv.keycloak.db.tz}
      username: ${sv.keycloak.db.username}
      password: ${sv.keycloak.db.password}


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${scoutventure.oauth2.issuer-uri}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
  endpoint:
    health:
      enabled: ${sv.monitoring.actuators.enabled}
      probes:
        enabled: ${sv.monitoring.actuators.enabled}
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

keycloak:
  server:
    contextPath: /api/v1/keycloak
    adminUser:
      username: ${sv.keycloak.adminUser.username}
      password: ${sv.keycloak.adminUser.password}
    realmImportFile: scoutventure-realm.json


sv:
  # Base Settings
  uri: "http://localhost:"
  nami:
    url: "https://nami.dpsg.de"
  # Database Settings
  db:
    url: localhost
    port: 5432
    useSSL: false
    username: scoutventure
    password: scoutventure
    db-name: scoutventure
    tz: Europe/Berlin
  # Security Settings
  keycloak:
    enabled: true
    adminUser:
      username: admin
      password: admin
    db:
      url: localhost
      port: 15432
      useSSL: false
      username: scoutventure
      password: scoutventure
      db-name: scoutventure_kc
      tz: Europe/Berlin

  # Monitoring
  monitoring:
    actuators:
      enabled: true

  # Other non-configurable settings
  liquibase:
    change-log: "classpath:/db/liquibase-changelog_testdata.xml"

  logging:
    file:
      size-limit: 5MB
    directory: logs

scoutventure:
  baseUrl: "http://localhost:4200"
  oauth2:
    issuer-uri: "http://localhost:38080/api/v1/keycloak/realms/master"
    clientId: "215538524160589831@anmelde-tool"
    secure-routes:
      - "/api"
  oidc:
    # The user with the superuser-sub will have full API access
    # The superuser-sub will be taken from the oauth2 jwt (subject) therefore it is none fungible
    superuser-sub: "215485842947375111"


springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger/swagger.html