server:
  port: 38080


spring:
  application:
    name: "ANMELDE_TOOL_BACKEND"

  datasource:
    url: jdbc:postgresql://${anmelde-tool.db.url}:${anmelde-tool.db.port}/${anmelde-tool.db.db-name}?useSSL=${anmelde-tool.db.useSSL}&serverTimezone=Europe/Berlin
    username: ${anmelde-tool.db.username}
    password: ${anmelde-tool.db.password}

  liquibase:
    change-log: "classpath:/db/liquibase-changelog_testdata.xml"
    drop-first: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${anmelde-tool.oauth2.issuer-uri}

anmelde-tool:
  baseUrl: "http://localhost:4200"
  oauth2:
    issuer-uri: "http://localhost:8080"
    clientId: "215538524160589831@anmelde-tool"
    secure-routes:
      - "/api"
  db:
    url: localhost
    port: 5432
    useSSL: false
    username: "anmelde_tool"
    password: "anmelde_tool"
    db-name: "anmelde_tool"
  logging:
    file:
      size-limit: 5MB
    directory: logs

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
