server:
  port: 38080


spring:
  application:
    name: "ScoutVenture API and IAM"

  datasource:
    url: jdbc:postgresql://${scoutventure.db.url}:${scoutventure.db.port}/${scoutventure.db.db-name}?useSSL=${scoutventure.db.useSSL}&serverTimezone=Europe/Berlin
    username: ${scoutventure.db.username}
    password: ${scoutventure.db.password}

  liquibase:
    change-log: "classpath:/db/liquibase-changelog_testdata.xml"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${scoutventure.oauth2.serverUrl}/realms/${scoutventure.oauth2.realm}


scoutventure:
  baseUrl: "http://localhost:4200"
  oauth2:
    provider: "keycloak"
    serverUrl: "http://localhost:8080"
    realm: "scoutventure"
    frontend:
      clientId: "d3b85e5bc91c40f2b8ea210b3f36f784@scoutventure-spa"
    backend:
      clientId: "72c5071a605e4c4aad900266fcefdc0e@scoutventure-backend"
      clientSecret: "pXIsJmKc5R8eRm2FxLx8I8XZ1tIo5VXy"
  oidc:
    # The user with the superuser-sub will have full API access
    # The superuser-sub will be taken from the oauth2 jwt (subject) therefore it is none fungible
    superuser-sub: "af3d69f5-0adc-40f7-ade6-90905ba3eed2"
  db:
    url: localhost
    port: 35432
    useSSL: false
    username: "scoutventure"
    password: "scoutventure"
    db-name: "scoutventure"
  nami:
    uri: "https://nami.dpsg.de"
  logging:
    file:
      size-limit: 5MB
    directory: logs

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger/swagger.html
