name: Build and Test Spring

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'spring/**'
      - '.github/workflows/build-and-test.spring.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'spring/**'
      - '.github/workflows/build-and-test.spring.yml'

env:
  JACOCO_ARTIFACT_NAME: jacoco-report


jobs:
  build:
    name: Build & Test Spring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Tests
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify jacoco:report

      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ./spring/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ./spring/target/site/jacoco/jacoco.csv