name: Pipeline for PRs

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  build-frontend:
    name: Build Angular Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ScoutVenture
    steps:
      - uses: actions/checkout@v4 # v4

      - name: Cache node modules
        uses: actions/cache@v4 # v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Clean Distribution Directory
        run: npm run ci:clean

      - name: Build Application
        run: npm run ci:build

  unit-test-frontend:
    name: Unit Test Frontend
    needs: build-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ScoutVenture
    steps:
      - uses: actions/checkout@v4 # v4

      - name: Cache node modules
        uses: actions/cache@v4 # v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Clean Distribution Directory
        run: npm run ci:clean

      - name: Run Unit Tests
        run: npm run ci:test

      - name: Upload converage reports to Codecov
        uses: codecov/codecov-action@v5 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/frontend/Scoutventure/coverage/cobertura/cobertura-coverage.xml
          flags: Frontend-Unit-Test
          fail_ci_if_error: true

  build-backend:
    name: Build .NET Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./asp-net/ScoutVenture
    steps:
      - uses: actions/checkout@v4 # v4

      - name: Setup ..NET
        uses: actions/setup-dotnet@v4 # v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore
