name: Release Spring as Dockerimage

concurrency: release

on:
  push:
    tags:
      - v*
      
env:
  VERSION: ""
  ARTIFACT_NAME: anmelde-tool-spring

jobs:
  build-spring:
    name: Build Spring App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      
      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests -Dversion=${{env.VERSION}}
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target/*.jar
          
  build-docker-image:
    name: Build Docker Image and Upload to Registry
    needs: build-spring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
        
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      
      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          
      - name: Download Build Artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target
          
      - name: Login to Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ${{vars.DOCKER_REGISTRY_URL}}
          username: ${{vars.DOCKER_REGISTRY_USERNAME}}
          password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
          
      - name: Build and push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          push: true
          tags: |
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:latest
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:${{env.VERSION}}
          file: ./docker/spring/Dockerfile
