name: Release Spring as Dockerimage

concurrency: release

on:
  push:
    tags:
      - v*

env:
  VERSION: ""
  ARTIFACT_NAME: scoutventure-api

jobs:
  build-spring:
    name: Build Spring App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests -Dversion=${{env.VERSION}}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target/*.jar

  build-docker-image:
    name: Build Docker Image and Upload to Registry
    needs: build-spring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Download Build Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target

      - name: Login to Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ${{vars.DOCKER_REGISTRY_URL}}
          username: ${{vars.DOCKER_REGISTRY_USERNAME}}
          password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: |
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:latest
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:${{env.VERSION}}
          file: ./docker/spring/Dockerfile
