name: Release Spring as Dockerimage

concurrency: release

on:
  push:
    tags:
      - v*
      
env:
  VERSION: ""
  ARTIFACT_NAME: anmelde-tool-spring

jobs:
  build-spring:
    name: Build Spring App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      
      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Set up JDK 17
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests -Dversion=${{env.VERSION}}
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target/*.jar
          
  build-docker-image:
    name: Build Docker Image and Upload to Registry
    needs: build-spring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
        
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      
      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          
      - name: Download Build Artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target
          
      - name: Login to Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ${{vars.DOCKER_REGISTRY_URL}}
          username: ${{vars.DOCKER_REGISTRY_USERNAME}}
          password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
          
      - name: Build and push
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
        with:
          context: .
          push: true
          tags: |
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:latest
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:${{env.VERSION}}
          file: ./docker/spring/Dockerfile
